# Generated by Django 6.1.1 on 2026-10-02 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en curso', 'En curso'), ('terminado', 'Terminado')], default='solicitado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('impago', 'Impago'), ('pago parcial', 'Pago parcial'), ('pago total', 'Pago total')], default='impago', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicios.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.solicitudservicio')),
            ],
        ),
    ]
